oe-landingpage: # Online Anweisungen für Dozenten für VLU. vlu-lecturer.fachschaft.info
    build: .
    #image: oe-landingpage
    ports:
      - 5000:5000
    container_name: oe-landingpage
    restart: always
    volumes:
      - ${PWD}/oe-landingpage:/app/db
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.port=5000"
    #  - "traefik.frontend.rule=Host:oe.fachschaft.info"
    environment:
      - REGISTER_TOKEN=TestToken
      - DATA_FILE_PATH=/app/db/
      - SUPPORT_EMAIL=Email@example.com
      - MAIL_SUBJECT="Erstiwoche 2020"
      - MAIL_FROM="from@example.com"
      - MAIL_PASSWORD="password"
      - MAIL_SMTP_SERVER=example.com
      - MAIL_SMTP_SERVER_PORT=465
      
