baseURL = 'https://oe.fachschaft.info/'
defaultContentLanguage = 'de'

theme= "monochrome"

[languages]
  [languages.de]
    title = 'Orientierungseinheit 2022'
    contentDir = "content/de"
    languageName = "Deutsch"
    languageCode = 'de-DE'
    weight = 1
  [languages.en]
    title = 'Freshmen welcome 2022'
    contentDir = "content/en"
    languageName = "English"
    languageCode = 'en-UK'
    weight = 2

